-- Generated from dumping the ef core migration that created the users (don't actually run this one, it is just for notes)

--
-- PostgreSQL database dump
--

-- Dumped from database version 15.4
-- Dumped by pg_dump version 15.4

SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;

--
-- Name: dbo; Type: SCHEMA; Schema: -; Owner: dats_sa
--

CREATE SCHEMA dbo;


ALTER SCHEMA dbo OWNER TO dats_sa;

SET default_tablespace = '';

SET default_table_access_method = heap;

--
-- Name: aspnetroleclaim; Type: TABLE; Schema: dbo; Owner: dats_sa
--

CREATE TABLE dbo.aspnetroleclaim (
    id integer NOT NULL,
    roleid text NOT NULL,
    claimtype text,
    claimvalue text
);


ALTER TABLE dbo.aspnetroleclaim OWNER TO dats_sa;

--
-- Name: AspNetRoleClaims_id_seq; Type: SEQUENCE; Schema: dbo; Owner: dats_sa
--

ALTER TABLE dbo.aspnetroleclaim ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME dbo."AspNetRoleClaims_id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: aspnetuserclaim; Type: TABLE; Schema: dbo; Owner: dats_sa
--

CREATE TABLE dbo.aspnetuserclaim (
    id integer NOT NULL,
    userid text NOT NULL,
    claimtype text,
    claimvalue text
);


ALTER TABLE dbo.aspnetuserclaim OWNER TO dats_sa;

--
-- Name: AspNetUserClaims_id_seq; Type: SEQUENCE; Schema: dbo; Owner: dats_sa
--

ALTER TABLE dbo.aspnetuserclaim ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME dbo."AspNetUserClaims_id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: aspnetrole; Type: TABLE; Schema: dbo; Owner: dats_sa
--

CREATE TABLE dbo.aspnetrole (
    id text NOT NULL,
    name character varying(256),
    normalizedname character varying(256),
    concurrencystamp text
);


ALTER TABLE dbo.aspnetrole OWNER TO dats_sa;

--
-- Name: aspnetuser; Type: TABLE; Schema: dbo; Owner: dats_sa
--

CREATE TABLE dbo.aspnetuser (
    id text NOT NULL,
    username character varying(256),
    normalizedusername character varying(256),
    email character varying(256),
    normalizedemail character varying(256),
    emailconfirmed boolean NOT NULL,
    passwordhash text,
    securitystamp text,
    concurrencystamp text,
    phonenumber text,
    phonenumberconfirmed boolean NOT NULL,
    twofactorenabled boolean NOT NULL,
    lockoutend timestamp with time zone,
    lockoutenabled boolean NOT NULL,
    accessfailedcount integer NOT NULL
);


ALTER TABLE dbo.aspnetuser OWNER TO dats_sa;

--
-- Name: aspnetuserrole; Type: TABLE; Schema: dbo; Owner: dats_sa
--

CREATE TABLE dbo.aspnetuserrole (
    userid text NOT NULL,
    roleid text NOT NULL
);


ALTER TABLE dbo.aspnetuserrole OWNER TO dats_sa;

--
-- Name: aspnetusers; Type: TABLE; Schema: dbo; Owner: dats_sa
--

CREATE TABLE dbo.aspnetusers (
    loginprovider text NOT NULL,
    providerkey text NOT NULL,
    providerdisplayname text,
    userid text NOT NULL
);


ALTER TABLE dbo.aspnetusers OWNER TO dats_sa;

--
-- Name: aspnetusertoken; Type: TABLE; Schema: dbo; Owner: dats_sa
--

CREATE TABLE dbo.aspnetusertoken (
    userid text NOT NULL,
    loginprovider text NOT NULL,
    name text NOT NULL,
    value text
);


ALTER TABLE dbo.aspnetusertoken OWNER TO dats_sa;

--
-- Name: __EFMigrationsHistory; Type: TABLE; Schema: public; Owner: dats_sa
--

CREATE TABLE public."__EFMigrationsHistory" (
    migrationid character varying(150) NOT NULL,
    productversion character varying(32) NOT NULL
);


ALTER TABLE public."__EFMigrationsHistory" OWNER TO dats_sa;

--
-- Name: aspnetroleclaim pk_aspnetroleclaims; Type: CONSTRAINT; Schema: dbo; Owner: dats_sa
--

ALTER TABLE ONLY dbo.aspnetroleclaim
    ADD CONSTRAINT pk_aspnetroleclaims PRIMARY KEY (id);


--
-- Name: aspnetrole pk_aspnetroles; Type: CONSTRAINT; Schema: dbo; Owner: dats_sa
--

ALTER TABLE ONLY dbo.aspnetrole
    ADD CONSTRAINT pk_aspnetroles PRIMARY KEY (id);


--
-- Name: aspnetuserclaim pk_aspnetuserclaims; Type: CONSTRAINT; Schema: dbo; Owner: dats_sa
--

ALTER TABLE ONLY dbo.aspnetuserclaim
    ADD CONSTRAINT pk_aspnetuserclaims PRIMARY KEY (id);


--
-- Name: aspnetusers pk_aspnetuserlogins; Type: CONSTRAINT; Schema: dbo; Owner: dats_sa
--

ALTER TABLE ONLY dbo.aspnetusers
    ADD CONSTRAINT pk_aspnetuserlogins PRIMARY KEY (loginprovider, providerkey);


--
-- Name: aspnetuserrole pk_aspnetuserroles; Type: CONSTRAINT; Schema: dbo; Owner: dats_sa
--

ALTER TABLE ONLY dbo.aspnetuserrole
    ADD CONSTRAINT pk_aspnetuserroles PRIMARY KEY (userid, roleid);


--
-- Name: aspnetuser pk_aspnetusers; Type: CONSTRAINT; Schema: dbo; Owner: dats_sa
--

ALTER TABLE ONLY dbo.aspnetuser
    ADD CONSTRAINT pk_aspnetusers PRIMARY KEY (id);


--
-- Name: aspnetusertoken pk_aspnetusertokens; Type: CONSTRAINT; Schema: dbo; Owner: dats_sa
--

ALTER TABLE ONLY dbo.aspnetusertoken
    ADD CONSTRAINT pk_aspnetusertokens PRIMARY KEY (userid, loginprovider, name);


--
-- Name: __EFMigrationsHistory pk___efmigrationshistory; Type: CONSTRAINT; Schema: public; Owner: dats_sa
--

ALTER TABLE ONLY public."__EFMigrationsHistory"
    ADD CONSTRAINT pk___efmigrationshistory PRIMARY KEY (migrationid);


--
-- Name: EmailIndex; Type: INDEX; Schema: dbo; Owner: dats_sa
--

CREATE INDEX "EmailIndex" ON dbo.aspnetuser USING btree (normalizedemail);


--
-- Name: RoleNameIndex; Type: INDEX; Schema: dbo; Owner: dats_sa
--

CREATE UNIQUE INDEX "RoleNameIndex" ON dbo.aspnetrole USING btree (normalizedname);


--
-- Name: UserNameIndex; Type: INDEX; Schema: dbo; Owner: dats_sa
--

CREATE UNIQUE INDEX "UserNameIndex" ON dbo.aspnetuser USING btree (normalizedusername);


--
-- Name: ix_aspnetroleclaims_roleid; Type: INDEX; Schema: dbo; Owner: dats_sa
--

CREATE INDEX ix_aspnetroleclaims_roleid ON dbo.aspnetroleclaim USING btree (roleid);


--
-- Name: ix_aspnetuserclaims_userid; Type: INDEX; Schema: dbo; Owner: dats_sa
--

CREATE INDEX ix_aspnetuserclaims_userid ON dbo.aspnetuserclaim USING btree (userid);


--
-- Name: ix_aspnetuserlogins_userid; Type: INDEX; Schema: dbo; Owner: dats_sa
--

CREATE INDEX ix_aspnetuserlogins_userid ON dbo.aspnetusers USING btree (userid);


--
-- Name: ix_aspnetuserroles_roleid; Type: INDEX; Schema: dbo; Owner: dats_sa
--

CREATE INDEX ix_aspnetuserroles_roleid ON dbo.aspnetuserrole USING btree (roleid);


--
-- Name: aspnetroleclaim fk_aspnetroleclaims_aspnetroles_roleid; Type: FK CONSTRAINT; Schema: dbo; Owner: dats_sa
--

ALTER TABLE ONLY dbo.aspnetroleclaim
    ADD CONSTRAINT fk_aspnetroleclaims_aspnetroles_roleid FOREIGN KEY (roleid) REFERENCES dbo.aspnetrole(id) ON DELETE CASCADE;


--
-- Name: aspnetuserclaim fk_aspnetuserclaims_aspnetusers_userid; Type: FK CONSTRAINT; Schema: dbo; Owner: dats_sa
--

ALTER TABLE ONLY dbo.aspnetuserclaim
    ADD CONSTRAINT fk_aspnetuserclaims_aspnetusers_userid FOREIGN KEY (userid) REFERENCES dbo.aspnetuser(id) ON DELETE CASCADE;


--
-- Name: aspnetusers fk_aspnetuserlogins_aspnetusers_userid; Type: FK CONSTRAINT; Schema: dbo; Owner: dats_sa
--

ALTER TABLE ONLY dbo.aspnetusers
    ADD CONSTRAINT fk_aspnetuserlogins_aspnetusers_userid FOREIGN KEY (userid) REFERENCES dbo.aspnetuser(id) ON DELETE CASCADE;


--
-- Name: aspnetuserrole fk_aspnetuserroles_aspnetroles_roleid; Type: FK CONSTRAINT; Schema: dbo; Owner: dats_sa
--

ALTER TABLE ONLY dbo.aspnetuserrole
    ADD CONSTRAINT fk_aspnetuserroles_aspnetroles_roleid FOREIGN KEY (roleid) REFERENCES dbo.aspnetrole(id) ON DELETE CASCADE;


--
-- Name: aspnetuserrole fk_aspnetuserroles_aspnetusers_userid; Type: FK CONSTRAINT; Schema: dbo; Owner: dats_sa
--

ALTER TABLE ONLY dbo.aspnetuserrole
    ADD CONSTRAINT fk_aspnetuserroles_aspnetusers_userid FOREIGN KEY (userid) REFERENCES dbo.aspnetuser(id) ON DELETE CASCADE;


--
-- Name: aspnetusertoken fk_aspnetusertokens_aspnetusers_userid; Type: FK CONSTRAINT; Schema: dbo; Owner: dats_sa
--

ALTER TABLE ONLY dbo.aspnetusertoken
    ADD CONSTRAINT fk_aspnetusertokens_aspnetusers_userid FOREIGN KEY (userid) REFERENCES dbo.aspnetuser(id) ON DELETE CASCADE;


--
-- PostgreSQL database dump complete
--

